# -*- coding: utf-8 -*-
"""pinn_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AX0wn4Fo2mrvsh3OPd9SwqvjbRsDPZE3
"""

import os
import io
import math
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

from google.colab import files

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

torch.manual_seed(42)
np.random.seed(42)

"""Geometry and experiment settings"""

# Beam geometry
L = 126.06e-3          # beam length [m]
width = 10.13e-3       # width [m]
height = 0.95e-3       # thickness / height [m]
rho = 8216.0  # density [kg/m^3] -> set your actual value

# Choose bending axis:
# "weak"  -> I = width * height^3 / 12
# "strong"-> I = height * width^3 / 12
bending_axis = "weak"

# Measurement location of FRF
x_meas = L          # usually tip measurement

# Known tip mass
# steel beam directly excited: m_tip = 0.0
# plastic beam with attached metal piece: set known mass here
m_tip = 10e-3       # [kg]

# Initial guesses for unknowns
E0_init = 70e9      # [Pa]
eta_init = 0.01     # [-]
kx_init = 1e6       # [N/m]
kphi_init = 1e2     # [N·m/rad]
F_init = 1.0        # [N]

# Synthetic reference values (used only if you generate synthetic data)
E0_true = 70e9
eta_true = 0.01
kx_true = 1e8
kphi_true = 1e8
F_true = 1.0

# Data / training options
use_synthetic_as_training_data = True   # True = train on synthetic data first
save_processed_csv = True
processed_csv_name = "processed_frf_data.csv"

# Plot options
plot_in_db = True
eps_db = 1e-16

# Sanity print
A = width * height
if bending_axis.lower() == "weak":
    I = width * height**3 / 12.0
elif bending_axis.lower() == "strong":
    I = height * width**3 / 12.0
else:
    raise ValueError("bending_axis must be 'weak' or 'strong'")

print(f"L       = {L:.6e} m")
print(f"width   = {width:.6e} m")
print(f"height  = {height:.6e} m")
print(f"rho     = {rho:.6e} kg/m^3")
print(f"A       = {A:.6e} m^2")
print(f"I       = {I:.6e} m^4")
print(f"x_meas  = {x_meas:.6e} m")
print(f"m_tip   = {m_tip:.6e} kg")
print(f"axis    = {bending_axis}")

"""Forward model from beam_theories_changes.py"""

def area_and_inertia(width, height, bending_axis="weak"):
    A = width * height
    if bending_axis.lower() == "weak":
        I = width * height**3 / 12.0
    elif bending_axis.lower() == "strong":
        I = height * width**3 / 12.0
    else:
        raise ValueError("bending_axis must be 'weak' or 'strong'")
    return A, I


def euler_beam_changes_forward(
    f_hz,
    L,
    width,
    height,
    rho,
    E0,
    eta,
    F_tip,
    m_tip=0.0,
    k_phi=0.0,
    k_x=0.0,
    x_meas=None,
    bending_axis="weak",
):
    """
    Forward model consistent with the ACTIVE implementation in beam_theories_changes.py.

    Convention used here:
        EI w''(0) + k_phi w'(0) = 0
        EI w'''(0) + k_x   w(0) = 0
        w''(L) = 0
        EI w'''(L) + m_tip * omega^2 * w(L) + F_tip = 0

    The RHS form implemented in the matrix solve is:
        M c = [0, 0, 0, -F_tip]^T

    Returns:
        f_hz : (N,)
        v    : (N,) complex velocity FRF at x_meas
    """
    if x_meas is None:
        x_meas = L

    f_hz = np.asarray(f_hz, dtype=float).reshape(-1)
    A, I = area_and_inertia(width, height, bending_axis)

    v = np.zeros(len(f_hz), dtype=np.complex128)

    E_complex = E0 * (1.0 + 1j * eta)

    for idx, f in enumerate(f_hz):
        omega = 2.0 * np.pi * f
        kappa = (omega**2 * rho * A / (E_complex * I))**0.25

        lam_1 = kappa
        lam_2 = 1j * kappa
        lam_3 = -kappa
        lam_4 = -1j * kappa

        M = np.array([
            [E_complex*I*lam_1**2 + k_phi*lam_1,
             E_complex*I*lam_2**2 + k_phi*lam_2,
             E_complex*I*lam_3**2 + k_phi*lam_3,
             E_complex*I*lam_4**2 + k_phi*lam_4],

            [E_complex*I*lam_1**3 + k_x,
             E_complex*I*lam_2**3 + k_x,
             E_complex*I*lam_3**3 + k_x,
             E_complex*I*lam_4**3 + k_x],

            [lam_1**2 * np.exp(lam_1 * L),
             lam_2**2 * np.exp(lam_2 * L),
             lam_3**2 * np.exp(lam_3 * L),
             lam_4**2 * np.exp(lam_4 * L)],

            [(E_complex*I*lam_1**3 + m_tip*omega**2) * np.exp(lam_1 * L),
             (E_complex*I*lam_2**3 + m_tip*omega**2) * np.exp(lam_2 * L),
             (E_complex*I*lam_3**3 + m_tip*omega**2) * np.exp(lam_3 * L),
             (E_complex*I*lam_4**3 + m_tip*omega**2) * np.exp(lam_4 * L)],
        ], dtype=np.complex128)

        rhs = np.array([0.0, 0.0, 0.0, -F_tip], dtype=np.complex128)

        c = np.linalg.solve(M, rhs)

        w_x = (
            c[0] * np.exp(lam_1 * x_meas) +
            c[1] * np.exp(lam_2 * x_meas) +
            c[2] * np.exp(lam_3 * x_meas) +
            c[3] * np.exp(lam_4 * x_meas)
        )

        # velocity = i * omega * displacement
        v[idx] = 1j * omega * w_x

    return f_hz, v

"""This cell expects one of these common formats:


* .npz with keys like freq, f, frequency and frf, V, velocity
* .npy containing either:
complex FRF only, or a dict-like object with frequency and FRF



"""

# Upload your experimental .npy or .npz file
uploaded = files.upload()
uploaded_name = list(uploaded.keys())[0]
print("Uploaded:", uploaded_name)

"""Experimental data parser and cleanup"""

def _pick_first_key(d, candidates):
    for c in candidates:
        if c in d:
            return c
    return None


def load_experimental_frf(path, x_meas):
    ext = os.path.splitext(path)[1].lower()

    # expanded key candidates
    freq_candidates = ["freq", "f", "frequency", "f_hz", "freq_s1", "freq_s2"]
    frf_candidates  = ["frf", "V", "velocity", "response", "H", "s1_fft", "s2_fft"]
    real_candidates = ["real", "V_real", "vr", "Re"]
    imag_candidates = ["imag", "V_imag", "vi", "Im"]

    if ext == ".npz":
        data = np.load(path, allow_pickle=True)
        print("NPZ keys:", list(data.keys()))

        f_key = _pick_first_key(data, freq_candidates)
        frf_key = _pick_first_key(data, frf_candidates)

        if f_key is not None and frf_key is not None:
            f_hz = np.asarray(data[f_key]).reshape(-1).astype(float)
            V = np.asarray(data[frf_key]).reshape(-1)

            # if FRF is not complex, try to interpret shape
            if not np.iscomplexobj(V):
                raise ValueError(
                    f"Found FRF key '{frf_key}', but array is not complex. "
                    "Please inspect its structure."
                )

        else:
            real_key = _pick_first_key(data, real_candidates)
            imag_key = _pick_first_key(data, imag_candidates)

            if f_key is None or real_key is None or imag_key is None:
                raise ValueError(
                    f"Could not parse NPZ structure. Available keys: {list(data.keys())}"
                )

            f_hz = np.asarray(data[f_key]).reshape(-1).astype(float)
            V = np.asarray(data[real_key]).reshape(-1) + 1j * np.asarray(data[imag_key]).reshape(-1)

    elif ext == ".npy":
        arr = np.load(path, allow_pickle=True)

        # dict saved inside .npy
        if hasattr(arr, "item"):
            try:
                data = arr.item()
            except Exception:
                data = None
        else:
            data = None

        if isinstance(data, dict):
            print("NPY dict keys:", list(data.keys()))

            f_key = _pick_first_key(data, freq_candidates)
            frf_key = _pick_first_key(data, frf_candidates)

            if f_key is not None and frf_key is not None:
                f_hz = np.asarray(data[f_key]).reshape(-1).astype(float)
                V = np.asarray(data[frf_key]).reshape(-1)

                if not np.iscomplexobj(V):
                    raise ValueError(
                        f"Found FRF key '{frf_key}', but array is not complex. "
                        "Please inspect its structure."
                    )

            else:
                real_key = _pick_first_key(data, real_candidates)
                imag_key = _pick_first_key(data, imag_candidates)

                if f_key is None or real_key is None or imag_key is None:
                    raise ValueError(
                        f"Could not parse NPY dict structure. Available keys: {list(data.keys())}"
                    )

                f_hz = np.asarray(data[f_key]).reshape(-1).astype(float)
                V = np.asarray(data[real_key]).reshape(-1) + 1j * np.asarray(data[imag_key]).reshape(-1)

        else:
            raise ValueError(
                "Plain .npy array without frequency information is ambiguous. "
                "Please provide .npz or .npy dict with frequency + FRF."
            )

    else:
        raise ValueError("Only .npy and .npz are supported in this notebook.")

    # Basic checks
    f_hz = np.asarray(f_hz).reshape(-1)
    V = np.asarray(V).reshape(-1)

    if len(f_hz) != len(V):
        raise ValueError(
            f"Frequency and FRF lengths do not match: len(f_hz)={len(f_hz)}, len(V)={len(V)}"
        )

    # finite values only
    mask = np.isfinite(f_hz) & np.isfinite(V.real) & np.isfinite(V.imag)
    f_hz = f_hz[mask]
    V = V[mask]

    # non-negative frequencies only
    mask = f_hz >= 0.0
    f_hz = f_hz[mask]
    V = V[mask]

    # sort
    order = np.argsort(f_hz)
    f_hz = f_hz[order]
    V = V[order]

    # remove duplicate frequencies by averaging complex values
    df = pd.DataFrame({
        "f_hz": f_hz,
        "V_real": V.real,
        "V_imag": V.imag
    })
    df = df.groupby("f_hz", as_index=False).mean()

    f_hz = df["f_hz"].to_numpy()
    V = df["V_real"].to_numpy() + 1j * df["V_imag"].to_numpy()

    x = np.full_like(f_hz, fill_value=x_meas, dtype=float)

    return f_hz, x, V

"""Optional CSV export of cleaned experimental data"""

if save_processed_csv:
    df_exp = pd.DataFrame({
        "x": x_exp,
        "f_hz": f_exp_hz,
        "V_real": V_exp.real,
        "V_imag": V_exp.imag,
        "V_mag": np.abs(V_exp),
        "V_phase_rad": np.angle(V_exp),
    })
    df_exp.to_csv(processed_csv_name, index=False)
    print(f"Saved cleaned experimental data to: {processed_csv_name}")

"""Generate synthetic FRF on the experimental frequency vector"""

f_syn_hz, V_syn = euler_beam_changes_forward(
    f_hz=f_exp_hz,            # USE EXPERIMENTAL FREQUENCY VECTOR DIRECTLY
    L=L,
    width=width,
    height=height,
    rho=rho,
    E0=E0_true,
    eta=eta_true,
    F_tip=F_true,
    m_tip=m_tip,
    k_phi=kphi_true,
    k_x=kx_true,
    x_meas=x_meas,
    bending_axis=bending_axis,
)

print("Synthetic data generated on experimental frequency grid.")

Plot experimental data only

fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

if plot_in_db:
    axs[0].plot(f_exp_hz, 20*np.log10(np.abs(V_exp) + eps_db))
    axs[0].set_ylabel("Magnitude [dB]")
else:
    axs[0].plot(f_exp_hz, np.abs(V_exp))
    axs[0].set_ylabel("Magnitude")

axs[0].set_title("Experimental FRF")

axs[1].plot(f_exp_hz, np.unwrap(np.angle(V_exp)))
axs[1].set_ylabel("Phase [rad]")
axs[1].set_xlabel("Frequency [Hz]")

plt.tight_layout()
plt.show()

"""Plot synthetic data only"""

fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

if plot_in_db:
    axs[0].plot(f_syn_hz, 20*np.log10(np.abs(V_syn) + eps_db))
    axs[0].set_ylabel("Magnitude [dB]")
else:
    axs[0].plot(f_syn_hz, np.abs(V_syn))
    axs[0].set_ylabel("Magnitude")

axs[0].set_title("Synthetic FRF from beam_theories_changes convention")

axs[1].plot(f_syn_hz, np.unwrap(np.angle(V_syn)))
axs[1].set_ylabel("Phase [rad]")
axs[1].set_xlabel("Frequency [Hz]")

plt.tight_layout()
plt.show()

"""Overlap plots: experimental vs synthetic"""

fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

if plot_in_db:
    axs[0].plot(f_exp_hz, 20*np.log10(np.abs(V_exp) + eps_db), label="Experimental")
    axs[0].plot(f_syn_hz, 20*np.log10(np.abs(V_syn) + eps_db), "--", label="Synthetic")
    axs[0].set_ylabel("Magnitude [dB]")
else:
    axs[0].plot(f_exp_hz, np.abs(V_exp), label="Experimental")
    axs[0].plot(f_syn_hz, np.abs(V_syn), "--", label="Synthetic")
    axs[0].set_ylabel("Magnitude")

axs[0].legend()
axs[0].set_title("Experimental vs Synthetic FRF")

axs[1].plot(f_exp_hz, np.unwrap(np.angle(V_exp)), label="Experimental")
axs[1].plot(f_syn_hz, np.unwrap(np.angle(V_syn)), "--", label="Synthetic")
axs[1].set_ylabel("Phase [rad]")
axs[1].set_xlabel("Frequency [Hz]")
axs[1].legend()

plt.tight_layout()
plt.show()

"""## Choose training data
Start with synthetic data first. Later set use_synthetic_as_training_data = False to train on experiment.
"""

if use_synthetic_as_training_data:
    f_train_hz = f_syn_hz.copy()
    x_train = np.full_like(f_train_hz, x_meas, dtype=float)
    V_train = V_syn.copy()
    print("Training data = SYNTHETIC")
else:
    f_train_hz = f_exp_hz.copy()
    x_train = x_exp.copy()
    V_train = V_exp.copy()
    print("Training data = EXPERIMENTAL")

omega_train = 2.0 * np.pi * f_train_hz

"""Torch tensors and normalization helpers"""

# Training data tensors
x_train_t = torch.tensor(x_train, dtype=torch.float32, device=device).view(-1, 1)
omega_train_t = torch.tensor(omega_train, dtype=torch.float32, device=device).view(-1, 1)
Vr_train_t = torch.tensor(V_train.real, dtype=torch.float32, device=device).view(-1, 1)
Vi_train_t = torch.tensor(V_train.imag, dtype=torch.float32, device=device).view(-1, 1)

# Domain limits from experiment
omega_min = float(omega_train.min())
omega_max = float(omega_train.max())

print("omega_min =", omega_min)
print("omega_max =", omega_max)


def normalize_x(x):
    # map [0, L] -> [-1, 1]
    return 2.0 * x / L - 1.0


def normalize_omega(omega):
    # map [omega_min, omega_max] -> [-1, 1]
    return 2.0 * (omega - omega_min) / (omega_max - omega_min) - 1.0

"""PINN model"""

class PINN(nn.Module):
    """
    Input:  (x, omega)
    Output: (W_real, W_imag)
    """
    def __init__(self, layers=[2, 128, 128, 128, 128, 2]):
        super().__init__()
        self.layers = nn.ModuleList()
        for i in range(len(layers) - 1):
            self.layers.append(nn.Linear(layers[i], layers[i + 1]))
        self.act = nn.Tanh()

    def forward(self, x, omega):
        x_n = normalize_x(x)
        w_n = normalize_omega(omega)
        z = torch.cat([x_n, w_n], dim=1)

        for layer in self.layers[:-1]:
            z = self.act(layer(z))

        out = self.layers[-1](z)
        Wr = out[:, 0:1]
        Wi = out[:, 1:2]
        return Wr, Wi


pinn = PINN().to(device)
print(pinn)

"""## Trainable physical parameters
All unknowns are constrained positive with softplus.
"""

def inv_softplus(y):
    y = np.asarray(y, dtype=np.float64)
    return np.log(np.exp(y) - 1.0)

# Raw trainable parameters
E0_raw   = nn.Parameter(torch.tensor([inv_softplus(E0_init)], dtype=torch.float32, device=device))
eta_raw  = nn.Parameter(torch.tensor([inv_softplus(eta_init)], dtype=torch.float32, device=device))
kx_raw   = nn.Parameter(torch.tensor([inv_softplus(kx_init)], dtype=torch.float32, device=device))
kphi_raw = nn.Parameter(torch.tensor([inv_softplus(kphi_init)], dtype=torch.float32, device=device))
F_raw    = nn.Parameter(torch.tensor([inv_softplus(F_init)], dtype=torch.float32, device=device))

trainable_params = list(pinn.parameters()) + [E0_raw, eta_raw, kx_raw, kphi_raw, F_raw]

optimizer = torch.optim.Adam(trainable_params, lr=1e-3)

"""Collocation points"""

# PDE collocation grid
Nx = 40
Nw = 40

x_c = torch.linspace(0.0, L, Nx, device=device).view(-1, 1)
omega_c = torch.linspace(omega_min, omega_max, Nw, device=device).view(-1, 1)

xx, ww = torch.meshgrid(x_c.squeeze(), omega_c.squeeze(), indexing="ij")
x_col = xx.reshape(-1, 1).clone().detach().requires_grad_(True)
omega_col = ww.reshape(-1, 1).clone().detach()

print("Collocation points:", x_col.shape[0])

"""Physics utilities"""

def grad(y, x):
    return torch.autograd.grad(
        y, x,
        grad_outputs=torch.ones_like(y),
        create_graph=True,
        retain_graph=True
    )[0]


def positive_params():
    E0 = torch.nn.functional.softplus(E0_raw) + 1e-12
    eta = torch.nn.functional.softplus(eta_raw) + 1e-12
    kx = torch.nn.functional.softplus(kx_raw) + 1e-12
    kphi = torch.nn.functional.softplus(kphi_raw) + 1e-12
    F = torch.nn.functional.softplus(F_raw) + 1e-12
    return E0, eta, kx, kphi, F

"""Loss function for pinn_v2
It matches the beam_theories_changes.py convention.
"""

# Fixed known geometry terms
A_t, I_t = area_and_inertia(width, height, bending_axis=bending_axis)
A_t = torch.tensor(A_t, dtype=torch.float32, device=device)
I_t = torch.tensor(I_t, dtype=torch.float32, device=device)
rho_t = torch.tensor(rho, dtype=torch.float32, device=device)
m_tip_t = torch.tensor(m_tip, dtype=torch.float32, device=device)


def pinn_v2_loss(
    pinn,
    x_col,
    omega_col,
    x_data,
    omega_data,
    Vr_data,
    Vi_data,
    w_pde=1.0,
    w_bc=10.0,
    w_data=1.0,
):
    E0, eta, kx, kphi, F = positive_params()

    # Complex modulus E = E0 * (1 + i eta)
    E_r = E0
    E_i = E0 * eta

    EI_r = E_r * I_t
    EI_i = E_i * I_t

    # ===================================
    # PDE residual
    # EI * W_xxxx - rho*A*omega^2 * W = 0
    # ===================================
    Wr, Wi = pinn(x_col, omega_col)

    Wr_x = grad(Wr, x_col)
    Wr_xx = grad(Wr_x, x_col)
    Wr_xxx = grad(Wr_xx, x_col)
    Wr_xxxx = grad(Wr_xxx, x_col)

    Wi_x = grad(Wi, x_col)
    Wi_xx = grad(Wi_x, x_col)
    Wi_xxx = grad(Wi_xx, x_col)
    Wi_xxxx = grad(Wi_xxx, x_col)

    omega2 = omega_col**2

    EI_W4_r = EI_r * Wr_xxxx - EI_i * Wi_xxxx
    EI_W4_i = EI_r * Wi_xxxx + EI_i * Wr_xxxx

    r_pde_r = EI_W4_r - rho_t * A_t * omega2 * Wr
    r_pde_i = EI_W4_i - rho_t * A_t * omega2 * Wi

    pde_loss = torch.mean(r_pde_r**2 + r_pde_i**2)

    # ===================================
    # Boundary conditions
    # Convention from beam_theories_changes active implementation:
    #
    # EI w''(0) + kphi w'(0) = 0
    # EI w'''(0) + kx  w(0)  = 0
    # w''(L) = 0
    # EI w'''(L) + m_tip*omega^2*w(L) + F = 0
    # ===================================
    omega_b = omega_col.detach()

    # x = 0
    x0 = torch.zeros_like(omega_b, requires_grad=True)
    Wr0, Wi0 = pinn(x0, omega_b)

    Wr0_x = grad(Wr0, x0)
    Wr0_xx = grad(Wr0_x, x0)
    Wr0_xxx = grad(Wr0_xx, x0)

    Wi0_x = grad(Wi0, x0)
    Wi0_xx = grad(Wi0_x, x0)
    Wi0_xxx = grad(Wi0_xx, x0)

    bc0_m_r = (EI_r * Wr0_xx - EI_i * Wi0_xx) + kphi * Wr0_x
    bc0_m_i = (EI_r * Wi0_xx + EI_i * Wr0_xx) + kphi * Wi0_x

    bc0_v_r = (EI_r * Wr0_xxx - EI_i * Wi0_xxx) + kx * Wr0
    bc0_v_i = (EI_r * Wi0_xxx + EI_i * Wr0_xxx) + kx * Wi0

    # x = L
    xL = torch.full_like(omega_b, fill_value=L, requires_grad=True)
    WrL, WiL = pinn(xL, omega_b)

    WrL_x = grad(WrL, xL)
    WrL_xx = grad(WrL_x, xL)
    WrL_xxx = grad(WrL_xx, xL)

    WiL_x = grad(WiL, xL)
    WiL_xx = grad(WiL_x, xL)
    WiL_xxx = grad(WiL_xx, xL)

    # w''(L) = 0
    bcL_m_r = WrL_xx
    bcL_m_i = WiL_xx

    # EI w'''(L) + m_tip*omega^2*w(L) + F = 0
    # F is taken as real scalar amplitude here
    bcL_v_r = (EI_r * WrL_xxx - EI_i * WiL_xxx) + m_tip_t * (omega_b**2) * WrL + F
    bcL_v_i = (EI_r * WiL_xxx + EI_i * WrL_xxx) + m_tip_t * (omega_b**2) * WiL

    bc_loss = torch.mean(
        bc0_m_r**2 + bc0_m_i**2 +
        bc0_v_r**2 + bc0_v_i**2 +
        bcL_m_r**2 + bcL_m_i**2 +
        bcL_v_r**2 + bcL_v_i**2
    )

    # ===================================
    # Data loss on velocity FRF
    # V = i * omega * W
    # => V_real = -omega * Wi
    # => V_imag =  omega * Wr
    # ===================================
    Wr_d, Wi_d = pinn(x_data, omega_data)

    Vp_r = -omega_data * Wi_d
    Vp_i =  omega_data * Wr_d

    data_loss = torch.mean((Vp_r - Vr_data)**2 + (Vp_i - Vi_data)**2)

    total_loss = w_pde * pde_loss + w_bc * bc_loss + w_data * data_loss

    logs = {
        "loss": total_loss.detach().item(),
        "pde": pde_loss.detach().item(),
        "bc": bc_loss.detach().item(),
        "data": data_loss.detach().item(),
        "E0": E0.detach().item(),
        "eta": eta.detach().item(),
        "kx": kx.detach().item(),
        "kphi": kphi.detach().item(),
        "F": F.detach().item(),
    }

    return total_loss, logs

"""Training loop"""

epochs = 5000

w_pde = 1.0
w_bc = 10.0
w_data = 1.0

history = {
    "loss": [],
    "pde": [],
    "bc": [],
    "data": [],
    "E0": [],
    "eta": [],
    "kx": [],
    "kphi": [],
    "F": [],
}

for epoch in range(epochs):
    optimizer.zero_grad()

    loss, logs = pinn_v2_loss(
        pinn=pinn,
        x_col=x_col,
        omega_col=omega_col,
        x_data=x_train_t,
        omega_data=omega_train_t,
        Vr_data=Vr_train_t,
        Vi_data=Vi_train_t,
        w_pde=w_pde,
        w_bc=w_bc,
        w_data=w_data,
    )

    loss.backward()
    optimizer.step()

    for k in history.keys():
        history[k].append(logs[k])

    if epoch % 200 == 0:
        print(
            f"Epoch {epoch:5d} | "
            f"Loss {logs['loss']:.3e} | "
            f"PDE {logs['pde']:.3e} | "
            f"BC {logs['bc']:.3e} | "
            f"Data {logs['data']:.3e} | "
            f"E0 {logs['E0']:.3e} | "
            f"eta {logs['eta']:.3e} | "
            f"kx {logs['kx']:.3e} | "
            f"kphi {logs['kphi']:.3e} | "
            f"F {logs['F']:.3e}"
        )

"""Plot training history"""

fig, axs = plt.subplots(2, 2, figsize=(14, 10))

axs[0, 0].plot(history["loss"], label="total")
axs[0, 0].plot(history["pde"], label="pde")
axs[0, 0].plot(history["bc"], label="bc")
axs[0, 0].plot(history["data"], label="data")
axs[0, 0].set_yscale("log")
axs[0, 0].legend()
axs[0, 0].set_title("Loss history")

axs[0, 1].plot(history["E0"])
axs[0, 1].set_title("E0")

axs[1, 0].plot(history["eta"], label="eta")
axs[1, 0].plot(history["F"], label="F")
axs[1, 0].legend()
axs[1, 0].set_title("eta and F")

axs[1, 1].plot(history["kx"], label="kx")
axs[1, 1].plot(history["kphi"], label="kphi")
axs[1, 1].legend()
axs[1, 1].set_title("kx and kphi")

plt.tight_layout()
plt.show()

"""Final identified parameters"""

E0_est, eta_est, kx_est, kphi_est, F_est = positive_params()

print("\n=== FINAL IDENTIFIED PARAMETERS ===")
print(f"E0   = {E0_est.item():.6e} Pa")
print(f"eta  = {eta_est.item():.6e}")
print(f"kx   = {kx_est.item():.6e} N/m")
print(f"kphi = {kphi_est.item():.6e} N*m/rad")
print(f"F    = {F_est.item():.6e} N")

"""Predict FRF from trained PINN at measurement point"""

pinn.eval()

with torch.no_grad():
    x_eval_t = torch.full_like(omega_train_t, fill_value=x_meas)
    Wr_pred, Wi_pred = pinn(x_eval_t, omega_train_t)

    Vp_r = (-omega_train_t * Wi_pred).cpu().numpy().reshape(-1)
    Vp_i = ( omega_train_t * Wr_pred).cpu().numpy().reshape(-1)
    V_pred = Vp_r + 1j * Vp_i

f_plot_hz = f_train_hz.copy()

"""Compare PINN prediction with training data"""

fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

if plot_in_db:
    axs[0].plot(f_plot_hz, 20*np.log10(np.abs(V_train) + eps_db), label="Training data")
    axs[0].plot(f_plot_hz, 20*np.log10(np.abs(V_pred) + eps_db), "--", label="PINN")
    axs[0].set_ylabel("Magnitude [dB]")
else:
    axs[0].plot(f_plot_hz, np.abs(V_train), label="Training data")
    axs[0].plot(f_plot_hz, np.abs(V_pred), "--", label="PINN")
    axs[0].set_ylabel("Magnitude")

axs[0].legend()
axs[0].set_title("PINN vs Training FRF")

axs[1].plot(f_plot_hz, np.unwrap(np.angle(V_train)), label="Training data")
axs[1].plot(f_plot_hz, np.unwrap(np.angle(V_pred)), "--", label="PINN")
axs[1].set_ylabel("Phase [rad]")
axs[1].set_xlabel("Frequency [Hz]")
axs[1].legend()

plt.tight_layout()
plt.show()

"""If training on synthetic, compare also against experimental"""

if use_synthetic_as_training_data:
    fig, axs = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

    if plot_in_db:
        axs[0].plot(f_exp_hz, 20*np.log10(np.abs(V_exp) + eps_db), label="Experimental")
        axs[0].plot(f_train_hz, 20*np.log10(np.abs(V_pred) + eps_db), "--", label="PINN")
        axs[0].set_ylabel("Magnitude [dB]")
    else:
        axs[0].plot(f_exp_hz, np.abs(V_exp), label="Experimental")
        axs[0].plot(f_train_hz, np.abs(V_pred), "--", label="PINN")
        axs[0].set_ylabel("Magnitude")

    axs[0].legend()
    axs[0].set_title("Experimental vs PINN")

    axs[1].plot(f_exp_hz, np.unwrap(np.angle(V_exp)), label="Experimental")
    axs[1].plot(f_train_hz, np.unwrap(np.angle(V_pred)), "--", label="PINN")
    axs[1].set_ylabel("Phase [rad]")
    axs[1].set_xlabel("Frequency [Hz]")
    axs[1].legend()

    plt.tight_layout()
    plt.show()

"""Save identified parameters and prediction"""

results = {
    "E0_est": float(E0_est.item()),
    "eta_est": float(eta_est.item()),
    "kx_est": float(kx_est.item()),
    "kphi_est": float(kphi_est.item()),
    "F_est": float(F_est.item()),
    "L": L,
    "width": width,
    "height": height,
    "rho": rho,
    "m_tip": m_tip,
    "x_meas": x_meas,
    "bending_axis": bending_axis,
}

with open("pinn_v2_identified_params.json", "w") as f:
    json.dump(results, f, indent=2)

df_pred = pd.DataFrame({
    "f_hz": f_plot_hz,
    "x": np.full_like(f_plot_hz, x_meas),
    "V_train_real": V_train.real,
    "V_train_imag": V_train.imag,
    "V_pred_real": V_pred.real,
    "V_pred_imag": V_pred.imag,
})

df_pred.to_csv("pinn_v2_prediction.csv", index=False)

print("Saved:")
print("- pinn_v2_identified_params.json")
print("- pinn_v2_prediction.csv")

"""## Important Notes for This Notebook

### 1. Tip Force

The force \(F\) is implemented as a **real positive scalar amplitude**.

This matches the assumption that the **excitation force amplitude is unknown** and must be identified during training.

If needed later, this can be extended to:

- **Complex forcing**
- **Frequency-dependent forcing**


### 2. Experimental Frequency “Outliers”

True frequency outliers are **rare**. The main practical issues encountered in experimental datasets are:

- duplicate frequency entries  
- unsorted frequency points  
- corrupted measurements  
- unit mismatches  

This notebook already performs the following preprocessing:

- removes invalid rows  
- sorts frequencies  
- averages duplicate frequency entries  

### 3. Recommended Workflow

For **`pinn_v2`**, follow this order:

1. **Train on synthetic data first**
2. **Verify that the PINN recovers the correct parameters**
3. **Then switch to experimental data**

This ensures the implementation is validated before using real measurements.



### 4. Important Physics Convention

This notebook follows the **active implementation in `beam_theories_changes.py`**, not the outdated comments.

The governing conventions used are:

- **Plus signs** at the **base spring boundary conditions**
- **Plus sign** in the **tip-mass boundary condition**
- External forcing enters through the **right-hand side term** = -F

"""